services:
  postgres:
    image: postgres:18
    container_name: gonote-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gonote
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
