services:
  postgres:
    image: postgres:18
    container_name: gonote-postgres
    environment:
      POSTGRES_DB: gonote
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d gonote'"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build: ./backend
    container_name: gonote-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy

  alloy: 
    image: grafana/alloy:latest
    container_name: gonote-alloy
    ports: 
      - "12345:12345"
    volumes: 
      - ./logs:/app/logs
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    container_name: gonote-loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
      - ./loki/config.yaml:/etc/loki/config.yaml
    command: 
      -config.file=/etc/loki/config.yaml


  grafana:
    image: grafana/grafana:latest
    container_name: gonote-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - alloy
      - loki

volumes:
  pgdata:
  backend-logs:
  loki-data:
  grafana-data:
  alloy-data:
